---
title: ""
layout: default
published: true
category: News
parent: news
meta_description: |
  COVID-19 Swiss vaccination breakthroughs report using BAG data
tags:
  - mirai
  - r
  - r_all
  - open_source
# If the news post should be shared automatically on social media (twitter or linkedin), then add the following social descriptions and hashtags fields as in example below.
social:
  description: |
    Another closer look at BAG data on COVID-19 vaccination #breakthroughs for the last 4 weeks in Switzerland. How effective has #vaccination been?
  hashtags: |
    #rstats #ggplot2 #covid19 #covidswitzerland #coronainfoch
# For r-bloggers / r-weekly posts (tag 'r'), set 'time' to be slightly earlier (within 1h)
# than the time (in Zurich) you will push the post to GitHub for going live
time: "14:20:00"
# The 'knit' field allows rendering from RStudio and should NOT be changed
# knit: (function(inputFile, encoding) postRmd::render_post(inputFile, ""))
# output:
#   html_document:
#     logo: img/mirai.png
# runtime: shiny
---
<!--more-->

```{r setup, include=FALSE}
# Default code chunk setup
knitr::opts_chunk$set(echo = FALSE, collapse = FALSE, comment = "")
# knitr::opts_chunk$set(echo = FALSE, prompt = FALSE, collapse = FALSE)
# def.chunk.hook  <- knitr::knit_hooks$get("chunk")
# important to fix it, as this is set dynamically by RStudio
options(width = 80)

# # we use a font size relative to the responsive body font size (em)
# table_css <- "border-collapse: separate; border-spacing: 0.25em; width: 100%; font-size: 0.7em; margin-bottom: 14.5px;"
# table_cell_css <- "white-space: nowrap; font-size: .95em;" # relative to the table_css

# libraries
# library(jsonlite)
# library(RCurl)
# library(dplyr)
# library(tidyr)
# library(stringr)
# library(ggplot2)
# library(plotly)
# library(tidyselect)
# library(scales)
# library(htmlTable)
# library(lubridate)
# library(kableExtra)
```


The ratio between the incidence of "Unvaccinated" vs "Fully Vaccinated" over time gives us a measure of how higher is the risk for the "Unvaccinated" is.

```{r ageclasses-pandemic-hosp-timeline_ratio, warning=FALSE, fig.width=6.667, fig.asp=0.6, dpi=150, out.extra='class="img-centered img-responsive"'}

DataRoll4W100kVac = DataRoll4W100k %>% filter(Status %in% grep("Fully", names(vac_levels()), value = TRUE)) %>%
  select(- pop) %>% rename(ValueVac = Value) #%>% pivot_wider(names_from  = Status, values_from = ValueVac)

DataRoll4W100kUnVac = DataRoll4W100k %>% filter(Status == "Unvac.") %>%
  select(- Status, - pop) %>% rename(ValueUnVac = Value)

DataRoll4W100kratio <- left_join(DataRoll4W100kVac, DataRoll4W100kUnVac, by = c("AsOfDate", "AgeClass", "Case" )) %>%
  mutate(Ratio = ValueUnVac / ValueVac) %>%
  mutate(Ratio = ifelse(is.nan(Ratio), NA, Ratio)) %>%
  mutate(Ratio = ifelse(is.infinite(Ratio), NA, Ratio)) %>%
  rename(Value = Ratio)

assign("DataRoll4W100kratio", DataRoll4W100kratio, pos = 1)
# LinePlotCovid(DataRoll4W100kratio %>% filter(Case == "Hospitalizations" & AsOfDate %in% last_timeline_weeks), FACET = "AgeClass", 
#               g_palette = c(rev(VaxCol)), 
#               title = "Time-line of Hospitalizations per Age class") 

```
